[package]
name = "winmedia_helper"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.61.3", features = ["Media_Control", "Storage_Streams"] }
tokio = { version = "1.45.1", features = ["full"] }
futures = "0.3.31"
base64 = "0.22.1"
