name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config curl wget git python3 python3-pip openjdk-11-jdk gcc-x86-64-linux-gnu g++-x86-64-linux-gnu libboost-system-dev libdbus-1-dev libdbus-1-3 libgtest-dev googletest

      - name: Build and test
        run: |
          cd native-hooks
          mkdir -p build && cd build
          cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build . --parallel
          ctest --output-on-failure -V

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Homebrew and dependencies
        run: |
          if ! command -v brew &>/dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.bash_profile
            eval "$(/opt/homebrew/bin/brew shellenv)"
          fi
          brew update
          brew install cmake boost googletest

      - name: Build and test
        run: |
          cd native-hooks
          mkdir -p build && cd build
          cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build . --parallel
          ctest --output-on-failure -V

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install vcpkg
        shell: powershell
        run: |
          if (-Not (Test-Path $env:VCPKG_ROOT)) {
            git clone https://github.com/microsoft/vcpkg.git $env:VCPKG_ROOT
            & "$env:VCPKG_ROOT\bootstrap-vcpkg.bat"
          }

      - name: Install dependencies via vcpkg
        shell: powershell
        run: |
          & "$env:VCPKG_ROOT\vcpkg.exe" install boost-system boost-beast cppwinrt gtest

      - name: Build and test
        shell: powershell
        run: |
          cd native-hooks
          mkdir build && cd build
          cmake .. -DBUILD_TESTS=ON -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release
          cmake --build . --parallel
          ctest --output-on-failure -V 